bscal/urls.py
from django.urls import path
from . import views

app_name = "bscal"
urlpatterns = [
    # /bscal/...
    path("", views.index, name="index"),
    path("limits/", views.limits, name="limits"),
    path("differentiation/", views.differentiation, name="differentiation"),
    # path("circle-standard-form/", views.cstdform, name="cstdform"),
    # path("circle-general-form/", views.cgrlform, name="cgrlform"),
    # path("parabola-finding-roots/", views.proots, name="proots")

]

checkmath/urls.py
from os import name
import genmath
import precal
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from django.views.generic.base import TemplateView
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^$', TemplateView.as_view(template_name='main/index.html'),
        name='home'),
    path('contact/', views.contact, name="contact"),
    url(r'^about/$', TemplateView.as_view(template_name='main/about.html'),
        name='about'),
    path('genmath/', include('genmath.urls')),
    path('precal/', include('precal.urls')),
    path('bscal/', include('bscal.urls'))
]

genmath/urls.py
from django.urls import path
from . import views

app_name = "genmath"
urlpatterns = [
    # /genmath/...
    path("", views.index, name="index"),
    path("function-evaluation/", views.fevaluation, name="fevaluation"),
    path("function-operations/", views.foperations, name="foperations"),
    path("function-composition/", views.fcomposite, name="fcomposite")

]

precal/urls.py
from django.urls import path
from . import views

app_name = "precal"
urlpatterns = [
    # /precal/...
    path("", views.index, name="index"),
    path("graphing/", views.graphing, name="graphing"),
    path("circle-standard-form/", views.cstdform, name="cstdform"),
    path("circle-general-form/", views.cgrlform, name="cgrlform"),
    path("parabola-finding-roots/", views.proots, name="proots")

]

precal/views.py
from django.shortcuts import render
import calculations as calc

# Create your views here.


def index(request):
    return render(request, 'precal/index.html')


def cstdform(request):
    if request.method == "POST":
        xcoord = request.POST.get("xcoord")
        ycoord = request.POST.get("ycoord")
        radius = request.POST.get("radius")

        if not xcoord or not ycoord or not radius:
            return render(request, "precal/cstdform.html", {
                'xcoord': '5',
                'ycoord': '-2',
                'radius': '3',
                'answer': 'Nope'
            })

        try:
            answer = calc.cstdform(xcoord, ycoord, radius)
        except:
            answer = 'Nope'

        
        return render(request, "precal/cstdform.html", {
            'xcoord': xcoord,
            'ycoord': ycoord,
            'radius': radius,
            'answer': answer
        })

    else:
        return render(request, "precal/cstdform.html", {
            'xcoord': '5',
            'ycoord': '-2',
            'radius': '3',
        })


def cgrlform(request):
    if request.method == "POST":
        xcoord = request.POST.get("xcoord")
        ycoord = request.POST.get("ycoord")
        radius = request.POST.get("radius")

        if not xcoord or not ycoord or not radius:
            return render(request, "precal/cgrlform.html", {
                'xcoord': '5',
                'ycoord': '-2',
                'radius': '3',
                'answer': 'Nope'
            })

        try:
            answer = calc.cgrlform(xcoord, ycoord, radius)
        except:
            answer = 'Nope'

        return render(request, "precal/cgrlform.html", {
            'xcoord': xcoord,
            'ycoord': ycoord,
            'radius': radius,
            'answer': answer
        })

    else:
        return render(request, "precal/cgrlform.html", {
            'xcoord': '5',
            'ycoord': '-2',
            'radius': '3',
        })


def graphing(request):
    if request.method == "POST":
        function = request.POST.get("function")

        if not function:
            return render(request, "precal/graphing.html", {
                'function': '',
                'answer': 'Nope'
            })

        return render(request, "precal/graphing.html", {
            'function': function
        })

    else:
        return render(request, "precal/graphing.html", {
            'function': '(x + 2)^2 + (y - 1)^2 = 25'
        })


def proots(request):
    if request.method == "POST":
        function = request.POST.get("function")

        if not function:
            return render(request, "precal/proots.html", {
                'function': '',
                'answer': 'Nope'
            })

        try:
            answer = calc.findx(function)
        except:
            answer = 'Nope'

        return render(request, "precal/proots.html", {
                'function': function,
                'answer': answer
            })

    else:
        return render(request, 'precal/proots.html', {
            'function': '2x^2 - 8x + 6',
        })

precal/templates/precal/cgrlform.html
{% extends "main/layout.html" %}
{% load static %}
{% block head %}
    <link rel="stylesheet" href="{% static 'genmath/styles.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'precal/styles.css' %}" type="text/css">
    <script src="{% static 'genmath/script-foperations.js' %}" type="text/javascript"></script>

    <!-- MathQuill -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/mathquill/0.10.1/mathquill.css" integrity="sha512-vPg9GqsZZ4LHv9BkFfZSXt7y4D7YaARPU2JFmpZug4EgtJJrumytMAFZkNSk2LSyqWir0TNbh2tBq7UJIMxvlA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/mathquill/0.10.1/mathquill.js" integrity="sha512-7jEhcM7FbjGHo1ejs1iw1J8FxcnACx7Z3lG29gQ5vTBe2U/gaQpzwjzPCyg32zTwXCloQDdorpLufmu0nBIqnQ==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
{% endblock %}

{% block title %}
    Circle: General Form - CheckMaths
{% endblock %}

{% block body %}
    <nav aria-label="breadcrumb" class="notnav">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="/">Home</a></li>
            <li class="breadcrumb-item"><a href="/precal">Pre-Calculus</a></li>
            <li class="breadcrumb-item active" aria-current="page">Circle: General Form</li>
        </ol>
    </nav>
    <div class="content-body">
        <div class="card-container">
            <div class="card text-dark mb-3" style="max-width: 18rem;">
                <div class="card-header">Take note</div>
                <div class="card-body">
                    <p class="card-text">
                        Use '()' for 2 or more digit exponents. <br>
                        <span class="math-text">
                            x^2a = <span class="math-disp">x^2a</span><br>
                            x^(2a) = <span class="math-disp">x^2^a</span>
                        </span>
                    </p>
                    <p class="card-text">
                        Use '()' for grouping. <br>
                        <span class="math-text">
                            4x - 2 / 2x + 8 <br>= <span class="math-disp">4x -\frac{2}{2x} + 8</span><br>
                            (4x - 2) / (2x + 8) <br>= <span class="math-disp">\frac{4x - 2}{2x + 8}</span>
                        </span>
                    </p>
                    <p class="card-text">
                        Use 'sqrt()' for square root.<br>
                        Leave the variables 's', 'q', 'r', 't' empty <br>
                        <span class="math-text">
                            5x + sqrt(x) = <span class="math-disp">5x + \sqrt x</span>
                        </span>
                    </p>
                    <p class="card-text">
                        Use 'Abs()' for square root (uppercase 'A').<br>
                        Leave the variables 'A', 'b', 's' empty <br>
                        <span class="math-text">
                            9 / Abs(-3) = <span class="math-disp">\frac{9}{|-3|}</span>
                        </span>
                    </p>
                    <h6 class="card-title">Need more help or having issues? <a href="/contact/"><span class="math-text">Click here!</span></a></h6>
                </div>
            </div>
        </div>
        <div class="content-body2">
            <div class="pagehead">
                <h6 class="subject">Pre-Calculus</h6>
                Circle: General Form
            </div>
            <div class="container">
                <form action="" method="POST" class="form" id="form">
                    {% csrf_token %}
                    <div class="centerinput">
                        <div>
                            Center = 
                            (<span><input type="text" name="xcoord" value="{{ xcoord }}" class="centercoord" placeholder="x" autocomplete="off"></span>, 
                            <span><input type="text" name="ycoord" value="{{ ycoord }}" class="centercoord" placeholder="y" autocomplete="off"></span>)
                        </div>
                    </div>
                    <div><br></div>
                    <div class="centerinput radiusinput">
                        <div>
                            Radius = <span><input type="text" name="radius" value="{{ radius }}" class="radius" autocomplete="off"></span>
                        </div>
                    </div>
                    <div><br></div>
                    <input type="submit" class="btn btn-primary" value="Solve"">
                    <div><br><br></div>
                </form>
            </div>
            <div><br></div>
        </div>
        <div class="card-container">
            <div class="card text-dark mb-3 card-right" style="max-width: 18rem;">
                <div class="card-header">Answer</div>
                <div class="card-body sample-eqs">
                    
                    {% if answer == "Nope" %}
                        <div class="answer">
                            <h6>Hmmm... Invalid input!</h6>
                            <h6>If your input is valid for you, <a href="/contact/"><span class="math-text">report the issue</span></a>.</h6>
                        </div>
                    {% elif answer %}
                        <div class="answer">
                            <h5><span class="math-disp">{{ answer }}</span></h5>
                        </div>
                    {% else %}
                        Click solve
                    {% endif %}

                    <!-- <p class="card-text">
                        <span class="math-text">
                            <span class="math-disp" id="sample1">3x - 5</span><br>
                        </span>
                    </p>        
                    <p class="card-text">
                        <span class="math-text">
                            <span class="math-disp" id="sample2">9a + 2^3^a^-^2</span><br>
                        </span>
                    </p>
                    <p class="card-text">
                        <span class="math-text">
                            <span class="math-disp" id="sample3">\frac{|6d|}{12f + 9u}</span><br>
                        </span>
                    </p>  
                    <br>
                    <h6 class="card-title">Need more help or having issues? <a href=""><span class="math-text">Click here!</span></a></h6> -->

                </div>
            </div>

            <div class="card-right next">
                <a href="{% url 'precal:proots' %}">Parabola: Finding Roots →</a>
            </div>
        </div>
    </div>

{% endblock %}

precal/templates/precal/cstdform.html
{% extends "main/layout.html" %}
{% load static %}
{% block head %}
    <link rel="stylesheet" href="{% static 'genmath/styles.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'precal/styles.css' %}" type="text/css">
    <script src="{% static 'genmath/script-foperations.js' %}" type="text/javascript"></script>

    <!-- MathQuill -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/mathquill/0.10.1/mathquill.css" integrity="sha512-vPg9GqsZZ4LHv9BkFfZSXt7y4D7YaARPU2JFmpZug4EgtJJrumytMAFZkNSk2LSyqWir0TNbh2tBq7UJIMxvlA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/mathquill/0.10.1/mathquill.js" integrity="sha512-7jEhcM7FbjGHo1ejs1iw1J8FxcnACx7Z3lG29gQ5vTBe2U/gaQpzwjzPCyg32zTwXCloQDdorpLufmu0nBIqnQ==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
{% endblock %}

{% block title %}
    Circle: Standard Form - CheckMaths
{% endblock %}

{% block body %}
    <nav aria-label="breadcrumb" class="notnav">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="/">Home</a></li>
            <li class="breadcrumb-item"><a href="/precal">Pre-Calculus</a></li>
            <li class="breadcrumb-item active" aria-current="page">Circle: Standard Form</li>
        </ol>
    </nav>
    <div class="content-body">
        <div class="card-container">
            <div class="card text-dark mb-3" style="max-width: 18rem;">
                <div class="card-header">Take note</div>
                <div class="card-body">
                    <p class="card-text">
                        Use '()' for 2 or more digit exponents. <br>
                        <span class="math-text">
                            x^2a = <span class="math-disp">x^2a</span><br>
                            x^(2a) = <span class="math-disp">x^2^a</span>
                        </span>
                    </p>
                    <p class="card-text">
                        Use '()' for grouping. <br>
                        <span class="math-text">
                            4x - 2 / 2x + 8 <br>= <span class="math-disp">4x -\frac{2}{2x} + 8</span><br>
                            (4x - 2) / (2x + 8) <br>= <span class="math-disp">\frac{4x - 2}{2x + 8}</span>
                        </span>
                    </p>
                    <p class="card-text">
                        Use 'sqrt()' for square root.<br>
                        Leave the variables 's', 'q', 'r', 't' empty <br>
                        <span class="math-text">
                            5x + sqrt(x) = <span class="math-disp">5x + \sqrt x</span>
                        </span>
                    </p>
                    <p class="card-text">
                        Use 'Abs()' for square root (uppercase 'A').<br>
                        Leave the variables 'A', 'b', 's' empty <br>
                        <span class="math-text">
                            9 / Abs(-3) = <span class="math-disp">\frac{9}{|-3|}</span>
                        </span>
                    </p>
                    <h6 class="card-title">Need more help or having issues? <a href="/contact/"><span class="math-text">Click here!</span></a></h6>
                </div>
            </div>
        </div>
        <div class="content-body2">
            <div class="pagehead">
                <h6 class="subject">Pre-Calculus</h6>
                Circle: Standard Form
            </div>
            <div class="container">
                <form action="" method="POST" class="form" id="form">
                    {% csrf_token %}
                    <div class="centerinput">
                        <div>
                            Center = 
                            (<span><input type="text" name="xcoord" value="{{ xcoord }}" class="centercoord" placeholder="x" autocomplete="off"></span>, 
                            <span><input type="text" name="ycoord" value="{{ ycoord }}" class="centercoord" placeholder="y" autocomplete="off"></span>)
                        </div>
                    </div>
                    <div><br></div>
                    <div class="centerinput radiusinput">
                        <div>
                            Radius = <span><input type="text" name="radius" value="{{ radius }}" class="radius" autocomplete="off"></span>
                        </div>
                    </div>
                    <div><br></div>
                    <input type="submit" class="btn btn-primary" value="Solve"">
                    <div><br><br></div>
                </form>
            </div>
            <div><br></div>
        </div>
        <div class="card-container">
            <div class="card text-dark mb-3 card-right" style="max-width: 18rem;">
                <div class="card-header">Answer</div>
                <div class="card-body sample-eqs">
                    
                    {% if answer == "Nope" %}
                        <div class="answer">
                            <h6>Hmmm... Invalid input!</h6>
                            <h6>If your input is valid for you, <a href="/contact/"><span class="math-text">report the issue</span></a>.</h6>
                        </div>
                    {% elif answer %}
                        <div class="answer">
                            <h5><span class="math-disp">{{ answer }}</span></h5>
                        </div>
                    {% else %}
                        Click solve
                    {% endif %}

                    <!-- <p class="card-text">
                        <span class="math-text">
                            <span class="math-disp" id="sample1">3x - 5</span><br>
                        </span>
                    </p>        
                    <p class="card-text">
                        <span class="math-text">
                            <span class="math-disp" id="sample2">9a + 2^3^a^-^2</span><br>
                        </span>
                    </p>
                    <p class="card-text">
                        <span class="math-text">
                            <span class="math-disp" id="sample3">\frac{|6d|}{12f + 9u}</span><br>
                        </span>
                    </p>  
                    <br>
                    <h6 class="card-title">Need more help or having issues? <a href=""><span class="math-text">Click here!</span></a></h6> -->

                </div>
            </div>

            <div class="card-right next">
                <a href="{% url 'precal:cgrlform' %}">Circle: General Form →</a>
            </div>
        </div>
    </div>

{% endblock %}

precal/templates/precal/fevaluation.html
{% extends "main/layout.html" %}
{% load static %}
{% block head %}
    <link rel="stylesheet" href="{% static 'genmath/styles.css' %}" type="text/css">
    <script src="{% static 'genmath/script-fevaluation.js' %}" type="text/javascript"></script>

    <!-- MathQuill -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/mathquill/0.10.1/mathquill.css" integrity="sha512-vPg9GqsZZ4LHv9BkFfZSXt7y4D7YaARPU2JFmpZug4EgtJJrumytMAFZkNSk2LSyqWir0TNbh2tBq7UJIMxvlA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/mathquill/0.10.1/mathquill.js" integrity="sha512-7jEhcM7FbjGHo1ejs1iw1J8FxcnACx7Z3lG29gQ5vTBe2U/gaQpzwjzPCyg32zTwXCloQDdorpLufmu0nBIqnQ==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
{% endblock %}

{% block title %}
    Evaluation of Functions - CheckMath
{% endblock %}

{% block body %}
    <nav aria-label="breadcrumb" class="notnav">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="/">Home</a></li>
            <li class="breadcrumb-item"><a href="/genmath">General Mathematics</a></li>
            <li class="breadcrumb-item active" aria-current="page">Evaluation of Functions</li>
        </ol>
    </nav>
    <div class="content-body">
        <div class="card-container">
            <div class="card text-dark mb-3" style="max-width: 18rem;">
                <div class="card-header">Take note</div>
                <div class="card-body">
                    <p class="card-text">
                        Use '()' for 2 or more digit exponents. <br>
                        <span class="math-text">
                            x^2a = <span class="math-disp">x^2a</span><br>
                            x^(2a) = <span class="math-disp">x^2^a</span>
                        </span>
                    </p>
                    <p class="card-text">
                        Use '()' for grouping. <br>
                        <span class="math-text">
                            4x - 2 / 2x + 8 <br>= <span class="math-disp">4x -\frac{2}{2x} + 8</span><br>
                            (4x - 2) / (2x + 8) <br>= <span class="math-disp">\frac{4x - 2}{2x + 8}</span>
                        </span>
                    </p>
                    <p class="card-text">
                        Use 'sqrt()' for square root.<br>
                        Leave the variables 's', 'q', 'r', 't' empty <br>
                        <span class="math-text">
                            5x + sqrt(x) = <span class="math-disp">5x + \sqrt x</span>
                        </span>
                    </p>
                    <p class="card-text">
                        Use 'Abs()' for square root (uppercase 'A').<br>
                        Leave the variables 'A', 'b', 's' empty <br>
                        <span class="math-text">
                            9 / Abs(-3) = <span class="math-disp">\frac{9}{|-3|}</span>
                        </span>
                    </p>
                    <h6 class="card-title">Need more help or having issues? <a href=""><span class="math-text">Click here!</span></a></h6>
                </div>
            </div>
        </div>
        <div class="content-body2">
            <div class="pagehead">
                <h6 class="subject">General Mathematics</h6>
                Evaluation of Functions
            </div>
            <div class="container">
                <form action="" method="POST" class="form" id="form">
                    {% csrf_token %}
                    <div class="form-floating">
                        <input type="text" class="form-control" id="functioninput" placeholder="Function" name="function" value="{{ function }}" autocomplete="off">
                        <label for="functioninput">Enter Function</label>
                    </div>
                    <div><br></div>
                    <!-- <div id="math-display">x^2 + 6x + 9</div> -->
                    <div class="variableinputs">
                        <div class="input-group mb-3 variableinput variable-x">
                            <span class="input-group-text">x =</span>
                            <input type="text" class="form-control vinput" value="{{ x }}" placeholder="Enter value of 'x'" name="variable-x" autocomplete="off">
                        </div>
                        {% if variables %}
                            {% for variable, value in variables.items %}
                                {% if variable == 'x' %}
                                    <!-- continue -->
                                {% else %}
                                    <div class="input-group mb-3 variableinput variable-{{ variable }}">
                                        <span class="input-group-text">{{ variable }} =</span>
                                        <input type="text" class="form-control vinput" value="{{ value }}" placeholder="Enter value of '{{ variable }}'" name="variable-{{ variable }}" autocomplete="off">
                                    </div>
                                {% endif %}
                            {% endfor %}
                        {% endif %}
                    </div>
                    <input type="submit" class="btn btn-primary" value="Solve"">
                </form>
            </div>
            <div><br></div>
        </div>
        <div class="card-container">
            <div class="card text-dark mb-3 card-right" style="max-width: 18rem;">
                <div class="card-header">Answer</div>
                <div class="card-body sample-eqs">
                    
                    {% if answer == "Nope" %}
                        <div class="answer">
                            <h6>Hmmm... Invalid input!</h6>
                            <h6>If your input is valid for you, <a href=""><span class="math-text">click here!</span></a></h6>
                        </div>
                    {% elif answer %}
                        <div class="answer">
                            <h5><span class="math-disp">{{ answer }}</h5>
                        </div>
                    {% else %}
                        Click solve
                    {% endif %}

                    <!-- <p class="card-text">
                        <span class="math-text">
                            <span class="math-disp" id="sample1">3x - 5</span><br>
                        </span>
                    </p>        
                    <p class="card-text">
                        <span class="math-text">
                            <span class="math-disp" id="sample2">9a + 2^3^a^-^2</span><br>
                        </span>
                    </p>
                    <p class="card-text">
                        <span class="math-text">
                            <span class="math-disp" id="sample3">\frac{|6d|}{12f + 9u}</span><br>
                        </span>
                    </p>  
                    <br>
                    <h6 class="card-title">Need more help or having issues? <a href=""><span class="math-text">Click here!</span></a></h6> -->

                </div>
            </div>
            <div class="card-right next">
                <a href="{% url 'genmath:foperations' %}">Operations on Functions →</a>
            </div>
        </div>
    </div>

{% endblock %}

precal/templates/precal/index.html
{% extends "main/layout.html" %}
{% load static %}
{% block head %}
    <link rel="stylesheet" href="{% static 'genmath/styles.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'precal/styles.css' %}" type="text/css">
{% endblock %}

{% block title %}
    Pre-Calculus - CheckMaths
{% endblock %}

{% block body %}
    <div class="pagehead">
        <h6 class="subject">Pre-Calculus</h6>
        Select a topic:
    </div>
    <div class="col-12 choices">
        <a href="{% url 'precal:graphing' %}" class="btn btn-primary">Graphing Conic Sections</a>
        <div class="topics">Circle</div>
        <a href="{% url 'precal:cstdform' %}" class="btn btn-primary">Standard Form</a>
        <a href="{% url 'precal:cgrlform' %}" class="btn btn-primary">General Form</a>
        <div class="topics">Parabola</div>
        <a href="{% url 'precal:proots' %}" class="btn btn-primary">Finding Roots</a>
        <div style="color: rgb(168, 169, 170);">
            <br>
            <br>
            Other topics are coming soon!
        </div>
        <!-- <a href="" class="btn btn-primary">Topic</a>
        <a href="" class="btn btn-primary">Topic</a>
        <a href="" class="btn btn-primary">Topic</a> -->
    </div>
    




{% endblock %}