bscal/urls.py
from django.urls import path
from . import views

app_name = "bscal"
urlpatterns = [
    # /bscal/...
    path("", views.index, name="index"),
    path("limits/", views.limits, name="limits"),
    path("differentiation/", views.differentiation, name="differentiation"),
    # path("circle-standard-form/", views.cstdform, name="cstdform"),
    # path("circle-general-form/", views.cgrlform, name="cgrlform"),
    # path("parabola-finding-roots/", views.proots, name="proots")

]

checkmath/urls.py
from os import name
import genmath
import precal
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from django.views.generic.base import TemplateView
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^$', TemplateView.as_view(template_name='main/index.html'),
        name='home'),
    path('contact/', views.contact, name="contact"),
    url(r'^about/$', TemplateView.as_view(template_name='main/about.html'),
        name='about'),
    path('genmath/', include('genmath.urls')),
    path('precal/', include('precal.urls')),
    path('bscal/', include('bscal.urls'))
]

genmath/urls.py
from django.urls import path
from . import views

app_name = "genmath"
urlpatterns = [
    # /genmath/...
    path("", views.index, name="index"),
    path("function-evaluation/", views.fevaluation, name="fevaluation"),
    path("function-operations/", views.foperations, name="foperations"),
    path("function-composition/", views.fcomposite, name="fcomposite")

]

precal/urls.py
from django.urls import path
from . import views

app_name = "precal"
urlpatterns = [
    # /precal/...
    path("", views.index, name="index"),
    path("graphing/", views.graphing, name="graphing"),
    path("circle-standard-form/", views.cstdform, name="cstdform"),
    path("circle-general-form/", views.cgrlform, name="cgrlform"),
    path("parabola-finding-roots/", views.proots, name="proots")

]

templates/main/about.html
{% extends "main/layout.html" %}
{% load static %}
{% block title %}
    About - CheckMaths
{% endblock %}

{% block body %}
    <!-- <div class="pagehead navbar-brand" id="checkmath" href="/">CheckMath</div> -->
    <div class="about">

        <div class="about-content">
            This website is for my co-senior high school students, <br> specifically for my friends
            who always ask me if their answer is correct :) <br><br>
            Developed by <a href="/contact/">Karemis</a>
            <div><br><br></div>

        </div>

    </div>

    <div class="py-2">
        <div class="modal" id="myModal">
            <div class="modal-dialog modal-dialog-centered">
                <div class="modal-content">
                    <div class="modal-header" style="justify-content: center;">
                        <h5 class="modal-title" style="color: rgb(197, 5, 5);">Disclaimer!</h5>
                        <!-- <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button> -->
                    </div>
                    <div class="modal-body" style="text-align: center;">
                        <p>
                            This website doesn't encourage any forms of academic dishonesty. <br><br>
                            Use at your own risk.
                        </p>
                    </div>
                    <div class="modal-footer" style="justify-content: center;">
                        <!-- <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button> -->
                        <button type="button" class="btn btn-primary" data-bs-dismiss="modal">Accept</button>
                    </div>
                </div>
            </div>
        </div>
    </div>


    <script type="text/javascript">
        var myModal = new bootstrap.Modal(document.getElementById('myModal'), {})
        myModal.toggle()
    </script>
{% endblock %}

templates/main/contact.html
{% extends "main/layout.html" %}
{% load static %}
{% block title %}
    Contact - CheckMaths
{% endblock %}

{% block body %}

    {% if invalid != False and invalid != '' %}
        <div class="alert alert-danger alert-dismissible fade show" role="alert">
            <strong>{{ invalid }}</strong>
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
    {% elif invalid == False %}
        <div class="alert alert-success alert-dismissible fade show" role="alert">
            <strong>Thank you for submitting!</strong>
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
    {% endif %}

    <div class="pagehead">
        <h5>Your feedback matters for the improvement of this website!</h5>
    </div>
    

    <form action="" method="POST">
        {% csrf_token %}
        <div class="contact-form">
            <div class="input-group mb-3 emailname">
                <!-- <span class="input-group-text label">Email:</span> -->
                <input type="text" class="form-control" placeholder="Email (optional)" name="email" aria-label="Email" value="{{ email }}">
                <div class="space"></div>
                <!-- <span class="input-group-text label">Name:</span> -->
                <input type="text" class="form-control" placeholder="Name (optional)" value="{{ name }}" name="name" aria-label="Name">
            </div>
            <div class="input-group mb-3">
                <span class="input-group-text">*Subject:</span>
                <input type="text" class="form-control" placeholder="Enter subject here" name="subject" value="{{ subject }}" aria-label="Username" required>
            </div>
            <div class="mb-3 message">
                <label for="exampleFormControlTextarea1" class="form-label">*Message</label>
                <textarea class="form-control" id="exampleFormControlTextarea1" name="message" rows="7" placeholder="Enter your message/concern/feedback here." value="{{ message }}" required>{{ message }}</textarea>
            </div>
            <div class="submit-container">
                <input type="submit" class="btn btn-primary form-submit" value="Submit"">
            </div>

            

        </div>
    </form>
{% endblock %}

templates/main/index.html
{% extends "main/layout.html" %}
{% load static %}
{% block title %}
    CheckMaths
{% endblock %}

{% block body %}
    <div class="pagehead">
        Select a subject:
    </div>

    <div class="row row-cols-1 row-cols-md-3 g-4">
        <div class="col">
            <div class="card h-100">
                <img src="{% static 'main/img/genmath.jpg' %}" class="card-img-top" alt="...">
                <div class="card-body">
                    <button type="button" onclick="location.href='{% url 'genmath:index' %}';" class="btn btn-outline-primary">General Mathematics</button>
                </div>
            </div>
        </div>
        <div class="col">
            <div class="card h-100">
                <img src="{% static 'main/img/precal.jpg' %}" class="card-img-top" alt="...">
                <div class="card-body">
                    <button type="button" onclick="location.href='{% url 'precal:index' %}';" class="btn btn-outline-primary">Pre-Calculus</button>
                </div>
            </div>
        </div>
        <div class="col">
            <div class="card h-100">
                <img src="{% static 'main/img/basiccal.jpg' %}" class="card-img-top" alt="...">
                <div class="card-body">
                    <button type="button" onclick="location.href='{% url 'bscal:index' %}';" class="btn btn-outline-primary">Basic Calculus</button>
                </div>
            </div>
        </div>
    </div>

    <div class="py-2">
        <div class="modal" id="myModal">
            <div class="modal-dialog modal-dialog-centered">
                <div class="modal-content">
                    <div class="modal-header" style="justify-content: center;">
                        <h5 class="modal-title" style="color: rgb(197, 5, 5);">Disclaimer!</h5>
                        <!-- <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button> -->
                    </div>
                    <div class="modal-body" style="text-align: center;">
                        <p>
                            This website doesn't encourage any forms of academic dishonesty. <br><br>
                            Use at your own risk.
                        </p>
                    </div>
                    <div class="modal-footer" style="justify-content: center;">
                        <!-- <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button> -->
                        <button type="button" class="btn btn-primary" data-bs-dismiss="modal">Accept</button>
                    </div>
                </div>
            </div>
        </div>
    </div>


    <script type="text/javascript">
        var myModal = new bootstrap.Modal(document.getElementById('myModal'), {})
        myModal.toggle()
    </script>
{% endblock %}

templates/main/layout.html
{% load static %}

<!DOCTYPE html>

<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">

        <!-- Bootstrap -->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

        <link rel="shortcut icon" type="image/png" href="{% static 'main/img/checkmathlogo.png' %}" />
        <link rel="stylesheet" href="{% static 'main/styles.css' %}" type="text/css">
        {% block head %}{% endblock %}
        <title>{% block title %}{% endblock %}</title>
    </head>
    <body>
        <nav class="navbar navbar-expand-lg navbar-light" id="navbar">
            <div class="container-fluid">
                <a class="navbar-brand" id="checkmath" href="/">CheckMaths</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse justify-content-end" id="navbarNavDropdown">
                    <ul class="navbar-nav">
                        <li class="nav-item">
                            <a class="nav-link" href="/">Home</a>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                Subjects
                            </a>
                            <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                                <li><a class="dropdown-item" href="{% url 'genmath:index' %}">General Mathematics</a></li>
                                <li><a class="dropdown-item" href="{% url 'precal:index' %}">Pre-Calculus</a></li>
                                <li><a class="dropdown-item" href="{% url 'bscal:index' %}">Basic Calculus</a></li>
                             </ul>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="/contact/">Contact</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="/about/">About</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>

        <div class="developed">
            <a href="/contact/">Karemis</a> Ⓒ 2021 All Rights Reserved
        </div>
        
        {% block body %}{% endblock %}
    </body>
</html>