bscal/urls.py
from django.urls import path
from . import views

app_name = "bscal"
urlpatterns = [
    # /bscal/...
    path("", views.index, name="index"),
    path("limits/", views.limits, name="limits"),
    path("differentiation/", views.differentiation, name="differentiation"),
    # path("circle-standard-form/", views.cstdform, name="cstdform"),
    # path("circle-general-form/", views.cgrlform, name="cgrlform"),
    # path("parabola-finding-roots/", views.proots, name="proots")

]

checkmath/urls.py
from os import name
import genmath
import precal
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from django.views.generic.base import TemplateView
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^$', TemplateView.as_view(template_name='main/index.html'),
        name='home'),
    path('contact/', views.contact, name="contact"),
    url(r'^about/$', TemplateView.as_view(template_name='main/about.html'),
        name='about'),
    path('genmath/', include('genmath.urls')),
    path('precal/', include('precal.urls')),
    path('bscal/', include('bscal.urls'))
]

genmath/urls.py
from django.urls import path
from . import views

app_name = "genmath"
urlpatterns = [
    # /genmath/...
    path("", views.index, name="index"),
    path("function-evaluation/", views.fevaluation, name="fevaluation"),
    path("function-operations/", views.foperations, name="foperations"),
    path("function-composition/", views.fcomposite, name="fcomposite")

]

genmath/views.py
from re import X
from checkmath.settings import BASE_DIR
from django.shortcuts import redirect, render
from django.http import HttpResponseRedirect
from django.urls import reverse
import calculations as calc
import os
import json


ROOT = os.path.abspath(os.curdir)

# Create your views here.
def index(request):
    return render(request, 'genmath/index.html')


def fevaluation(request):
    x = 4
    if request.method == "POST":
        function = request.POST.get("function")
        try:
            variables = json.loads(request.POST.get("variables"))
        except:
            return render(request, 'genmath/fevaluation.html', {
                'function': 'x^2 + 6x + 9',
                'x': x,
                'answer': 'Nope'
            })

        if 'x' not in variables:
            x = 0
        else:
            x = variables['x']

        if not function or not variables:
            return render(request, 'genmath/fevaluation.html', {
                'function': 'x^2 + 6x + 9',
                'x': x,
                'answer': 'Nope'
            })
        

        try:
            answer = calc.evaluate(function, variables)
        except:
            answer = "Nope"


        return render(request, 'genmath/fevaluation.html', {
            'function': function,
            'x': x,
            'variables': variables,
            'answer': answer
        })


    else:
        return render(request, 'genmath/fevaluation.html', {
            'x': x,
            'function': 'x^2 + 6x + 9'
        })


def foperations(request):
    selectedop = '1'
    if request.method == "POST":
        operations = {
            '1': '+',
            '2': '-',
            '3': '*',
            '4': '/'
        }

        try:
            function1 = request.POST.get("function1")
            function2 = request.POST.get("function2")
            x = request.POST.get("variable-x")
            operation = request.POST.get("operation")
            selectedop = 'option' + operation
        except:
            return render(request, 'genmath/foperations.html', {
                'function1': 'x^2 + 6x + 8',
                'function2': 'x + 2',
                'x': 'x',
                f'{selectedop}': 'selected',
                'answer': 'Nope'
            })

        if not function1 or not function2:
            return render(request, 'genmath/foperations.html', {
                'function1': '',
                'function2': '',
                'x': '',
                f'{selectedop}': 'selected',
                'answer': 'Nope'
            })

        if not x:
            x = 'x'

        if operation not in operations.keys():
            return render(request, 'genmath/foperations.html', {
                'function1': function1,
                'function2': function2,
                'x': x,
                f'{selectedop}': 'selected',
                'answer': 'Invalid operation! Maybe try not to inspect the element?'
            })

        for key, value in operations.items():
            if operation == key:
                operation = value

        try:
            answer = calc.operate(function1, function2, x, operation)
        except:
            answer = "Nope"


        return render(request, 'genmath/foperations.html', {
                'function1': function1,
                'function2': function2,
                'x': x,
                f'{selectedop}': 'selected',
                'answer': answer
            })

    else:
        return render(request, 'genmath/foperations.html', {
            'function1': 'x^2 + 6x + 8',
            'function2': 'x + 2',
            f'{selectedop}': 'selected',
            'x': 'x',
        })


def fcomposite(request):
    
    if request.method == "POST":

        try:
            function1 = request.POST.get("function1")
            function2 = request.POST.get("function2")
            x = request.POST.get("variable-x")
        except:
            return render(request, 'genmath/fcomposite.html', {
                'function1': '3x + 2',
                'function2': '2x^2 + 5',
                'x': '2',
                'answer': 'Nope'
            })

        if not function1 or not function2:
            return render(request, 'genmath/fcomposite.html', {
                'function1': '',
                'function2': '',
                'x': '',
                'answer': 'Nope'
            })

        if not x:
            x = 'x'

        try:
            answer = calc.composite(function1, function2, x)
        except:
            answer = "Nope"


        return render(request, 'genmath/fcomposite.html', {
                'function1': function1,
                'function2': function2,
                'x': x,
                'answer': answer
            })
    else:
        return render(request, 'genmath/fcomposite.html', {
                'function1': '3x + 2',
                'function2': '2x^2 + 5',
                'x': '2',
            })

genmath/templates/genmath/fcomposite.html
{% extends "main/layout.html" %}
{% load static %}
{% block head %}
    <link rel="stylesheet" href="{% static 'genmath/styles.css' %}" type="text/css">
    <script src="{% static 'genmath/script-foperations.js' %}" type="text/javascript"></script>

    <!-- MathQuill -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/mathquill/0.10.1/mathquill.css" integrity="sha512-vPg9GqsZZ4LHv9BkFfZSXt7y4D7YaARPU2JFmpZug4EgtJJrumytMAFZkNSk2LSyqWir0TNbh2tBq7UJIMxvlA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/mathquill/0.10.1/mathquill.js" integrity="sha512-7jEhcM7FbjGHo1ejs1iw1J8FxcnACx7Z3lG29gQ5vTBe2U/gaQpzwjzPCyg32zTwXCloQDdorpLufmu0nBIqnQ==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
{% endblock %}

{% block title %}
    Composition of Functions - CheckMaths
{% endblock %}

{% block body %}
    <nav aria-label="breadcrumb" class="notnav">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="/">Home</a></li>
            <li class="breadcrumb-item"><a href="/genmath">General Mathematics</a></li>
            <li class="breadcrumb-item active" aria-current="page">Composition of Functions</li>
        </ol>
    </nav>
    <div class="content-body">
        <div class="card-container">
            <div class="card text-dark mb-3" style="max-width: 18rem;">
                <div class="card-header">Take note</div>
                <div class="card-body">
                    <p class="card-text">
                        Use '()' for 2 or more digit exponents. <br>
                        <span class="math-text">
                            x^2a = <span class="math-disp">x^2a</span><br>
                            x^(2a) = <span class="math-disp">x^2^a</span>
                        </span>
                    </p>
                    <p class="card-text">
                        Use '()' for grouping. <br>
                        <span class="math-text">
                            4x - 2 / 2x + 8 <br>= <span class="math-disp">4x -\frac{2}{2x} + 8</span><br>
                            (4x - 2) / (2x + 8) <br>= <span class="math-disp">\frac{4x - 2}{2x + 8}</span>
                        </span>
                    </p>
                    <p class="card-text">
                        Use 'sqrt()' for square root.<br>
                        Leave the variables 's', 'q', 'r', 't' empty <br>
                        <span class="math-text">
                            5x + sqrt(x) = <span class="math-disp">5x + \sqrt x</span>
                        </span>
                    </p>
                    <p class="card-text">
                        Use 'Abs()' for square root (uppercase 'A').<br>
                        Leave the variables 'A', 'b', 's' empty <br>
                        <span class="math-text">
                            9 / Abs(-3) = <span class="math-disp">\frac{9}{|-3|}</span>
                        </span>
                    </p>
                    <h6 class="card-title">Need more help or having issues? <a href="/contact/"><span class="math-text">Click here!</span></a></h6>
                </div>
            </div>
        </div>
        <div class="content-body2">
            <div class="pagehead">
                <h6 class="subject">General Mathematics</h6>
                Composition of Functions
                <div style="font-size: 0.7rem;">Input your functions in terms of 'x'</div>
            </div>
            <div class="container">
                <form action="" method="POST" class="form" id="form">
                    {% csrf_token %}
                    <div class="form-floating">
                        <input type="text" class="form-control" id="functioninput1" placeholder="Function" name="function1" value="{{ function1 }}" autocomplete="off">
                        <label for="functioninput1">f(x)</label>
                    </div>
                    <div><br></div>
                    <div class="form-floating">
                        <input type="text" class="form-control" id="functioninput2" placeholder="Function" name="function2" value="{{ function2 }}" autocomplete="off">
                        <label for="functioninput2">g(x)</label>
                    </div>
                    <div><br></div>
                    <div class="input-group mb-3 variableinput variable-x foperations-x">
                        <span class="input-group-text">x =</span>
                        <input type="text" class="form-control vinput" value="{{ x }}" placeholder="Enter value of 'x'" name="variable-x" autocomplete="off">
                    </div>
                    <div><br></div>
                    <select class="form-select select-op" aria-label="Default select example" name="operation">
                        <option value="1" selected disabled>f(g(x))</option>
                    </select>
                    <div><br></div>
                    <input type="submit" class="btn btn-primary" value="Solve"">
                    <div><br><br></div>
                    <div style="font-size: 0.9rem; text-align: center;">
                        f(g(x)) is the same as (f ◦ g)(x)<br>
                        but not g(f(x)) or (g ◦ f)(x)
                    </div>
                </form>
            </div>
            <div><br></div>
        </div>
        <div class="card-container">
            <div class="card text-dark mb-3 card-right" style="max-width: 18rem;">
                <div class="card-header">Answer</div>
                <div class="card-body sample-eqs">
                    
                    {% if answer == "Nope" %}
                        <div class="answer">
                            <h6>Hmmm... Invalid input!</h6>
                            <h6>If your input is valid for you, <a href="/contact/"><span class="math-text">report the issue</span></a>.</h6>
                        </div>
                    {% elif answer %}
                        <div class="answer">
                            <h5><span class="math-disp">{{ answer }}</span></h5>
                        </div>
                    {% else %}
                        Click solve
                    {% endif %}

                    <!-- <p class="card-text">
                        <span class="math-text">
                            <span class="math-disp" id="sample1">3x - 5</span><br>
                        </span>
                    </p>        
                    <p class="card-text">
                        <span class="math-text">
                            <span class="math-disp" id="sample2">9a + 2^3^a^-^2</span><br>
                        </span>
                    </p>
                    <p class="card-text">
                        <span class="math-text">
                            <span class="math-disp" id="sample3">\frac{|6d|}{12f + 9u}</span><br>
                        </span>
                    </p>  
                    <br>
                    <h6 class="card-title">Need more help or having issues? <a href=""><span class="math-text">Click here!</span></a></h6> -->

                </div>
            </div>

        </div>
    </div>

{% endblock %}

genmath/templates/genmath/fevaluation.html
{% extends "main/layout.html" %}
{% load static %}
{% block head %}
    <link rel="stylesheet" href="{% static 'genmath/styles.css' %}" type="text/css">
    <script src="{% static 'genmath/script-fevaluation.js' %}" type="text/javascript"></script>

    <!-- MathQuill -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/mathquill/0.10.1/mathquill.css" integrity="sha512-vPg9GqsZZ4LHv9BkFfZSXt7y4D7YaARPU2JFmpZug4EgtJJrumytMAFZkNSk2LSyqWir0TNbh2tBq7UJIMxvlA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/mathquill/0.10.1/mathquill.js" integrity="sha512-7jEhcM7FbjGHo1ejs1iw1J8FxcnACx7Z3lG29gQ5vTBe2U/gaQpzwjzPCyg32zTwXCloQDdorpLufmu0nBIqnQ==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
{% endblock %}

{% block title %}
    Evaluation of Functions - CheckMaths
{% endblock %}

{% block body %}
    <nav aria-label="breadcrumb" class="notnav">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="/">Home</a></li>
            <li class="breadcrumb-item"><a href="/genmath">General Mathematics</a></li>
            <li class="breadcrumb-item active" aria-current="page">Evaluation of Functions</li>
        </ol>
    </nav>
    <div class="content-body">
        <div class="card-container">
            <div class="card text-dark mb-3" style="max-width: 18rem;">
                <div class="card-header">Take note</div>
                <div class="card-body">
                    <p class="card-text">
                        Use '()' for 2 or more digit exponents. <br>
                        <span class="math-text">
                            x^2a = <span class="math-disp">x^2a</span><br>
                            x^(2a) = <span class="math-disp">x^2^a</span>
                        </span>
                    </p>
                    <p class="card-text">
                        Use '()' for grouping. <br>
                        <span class="math-text">
                            4x - 2 / 2x + 8 <br>= <span class="math-disp">4x -\frac{2}{2x} + 8</span><br>
                            (4x - 2) / (2x + 8) <br>= <span class="math-disp">\frac{4x - 2}{2x + 8}</span>
                        </span>
                    </p>
                    <p class="card-text">
                        Use 'sqrt()' for square root.<br>
                        Leave the variables 's', 'q', 'r', 't' empty <br>
                        <span class="math-text">
                            5x + sqrt(x) = <span class="math-disp">5x + \sqrt x</span>
                        </span>
                    </p>
                    <p class="card-text">
                        Use 'Abs()' for square root (uppercase 'A').<br>
                        Leave the variables 'A', 'b', 's' empty <br>
                        <span class="math-text">
                            9 / Abs(-3) = <span class="math-disp">\frac{9}{|-3|}</span>
                        </span>
                    </p>
                    <h6 class="card-title">Need more help or having issues? <a href="/contact/"><span class="math-text">Click here!</span></a></h6>
                </div>
            </div>
        </div>
        <div class="content-body2">
            <div class="pagehead">
                <h6 class="subject">General Mathematics</h6>
                Evaluation of Functions
            </div>
            <div class="container">
                <form action="" method="POST" class="form" id="form">
                    {% csrf_token %}
                    <div class="form-floating">
                        <input type="text" class="form-control" id="functioninput" placeholder="Function" name="function" value="{{ function }}" autocomplete="off">
                        <label for="functioninput">Enter Function</label>
                    </div>
                    <div><br></div>
                    <!-- <div id="math-display">x^2 + 6x + 9</div> -->
                    <div class="variableinputs">
                        <div class="input-group mb-3 variableinput variable-x">
                            <span class="input-group-text">x =</span>
                            <input type="text" class="form-control vinput" value="{{ x }}" placeholder="Enter value of 'x'" name="variable-x" autocomplete="off">
                        </div>
                        {% if variables %}
                            {% for variable, value in variables.items %}
                                {% if variable == 'x' %}
                                    <!-- continue -->
                                {% else %}
                                    <div class="input-group mb-3 variableinput variable-{{ variable }}">
                                        <span class="input-group-text">{{ variable }} =</span>
                                        <input type="text" class="form-control vinput" value="{{ value }}" placeholder="Enter value of '{{ variable }}'" name="variable-{{ variable }}" autocomplete="off">
                                    </div>
                                {% endif %}
                            {% endfor %}
                        {% endif %}
                    </div>
                    <input type="submit" class="btn btn-primary" value="Solve"">
                </form>
            </div>
            <div><br></div>
        </div>
        <div class="card-container">
            <div class="card text-dark mb-3 card-right" style="max-width: 18rem;">
                <div class="card-header">Answer</div>
                <div class="card-body sample-eqs">
                    
                    {% if answer == "Nope" %}
                        <div class="answer">
                            <h6>Hmmm... Invalid input!</h6>
                            <h6>If your input is valid for you, <a href="/contact/"><span class="math-text">report the issue</span></a>.</h6>
                        </div>
                    {% elif answer %}
                        <div class="answer">
                            <h5><span class="math-disp">{{ answer }}</h5>
                        </div>
                    {% else %}
                        Click solve
                    {% endif %}

                    <!-- <p class="card-text">
                        <span class="math-text">
                            <span class="math-disp" id="sample1">3x - 5</span><br>
                        </span>
                    </p>        
                    <p class="card-text">
                        <span class="math-text">
                            <span class="math-disp" id="sample2">9a + 2^3^a^-^2</span><br>
                        </span>
                    </p>
                    <p class="card-text">
                        <span class="math-text">
                            <span class="math-disp" id="sample3">\frac{|6d|}{12f + 9u}</span><br>
                        </span>
                    </p>  
                    <br>
                    <h6 class="card-title">Need more help or having issues? <a href=""><span class="math-text">Click here!</span></a></h6> -->

                </div>
            </div>
            <div class="card-right next">
                <a href="{% url 'genmath:foperations' %}">Operations on Functions →</a>
            </div>
        </div>
    </div>

{% endblock %}

genmath/templates/genmath/foperations.html
{% extends "main/layout.html" %}
{% load static %}
{% block head %}
    <link rel="stylesheet" href="{% static 'genmath/styles.css' %}" type="text/css">
    <script src="{% static 'genmath/script-foperations.js' %}" type="text/javascript"></script>

    <!-- MathQuill -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/mathquill/0.10.1/mathquill.css" integrity="sha512-vPg9GqsZZ4LHv9BkFfZSXt7y4D7YaARPU2JFmpZug4EgtJJrumytMAFZkNSk2LSyqWir0TNbh2tBq7UJIMxvlA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/mathquill/0.10.1/mathquill.js" integrity="sha512-7jEhcM7FbjGHo1ejs1iw1J8FxcnACx7Z3lG29gQ5vTBe2U/gaQpzwjzPCyg32zTwXCloQDdorpLufmu0nBIqnQ==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
{% endblock %}

{% block title %}
    Operations on Functions - CheckMaths
{% endblock %}

{% block body %}
    <nav aria-label="breadcrumb" class="notnav">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="/">Home</a></li>
            <li class="breadcrumb-item"><a href="/genmath">General Mathematics</a></li>
            <li class="breadcrumb-item active" aria-current="page">Operations on Functions</li>
        </ol>
    </nav>
    <div class="content-body">
        <div class="card-container">
            <div class="card text-dark mb-3" style="max-width: 18rem;">
                <div class="card-header">Take note</div>
                <div class="card-body">
                    <p class="card-text">
                        Use '()' for 2 or more digit exponents. <br>
                        <span class="math-text">
                            x^2a = <span class="math-disp">x^2a</span><br>
                            x^(2a) = <span class="math-disp">x^2^a</span>
                        </span>
                    </p>
                    <p class="card-text">
                        Use '()' for grouping. <br>
                        <span class="math-text">
                            4x - 2 / 2x + 8 <br>= <span class="math-disp">4x -\frac{2}{2x} + 8</span><br>
                            (4x - 2) / (2x + 8) <br>= <span class="math-disp">\frac{4x - 2}{2x + 8}</span>
                        </span>
                    </p>
                    <p class="card-text">
                        Use 'sqrt()' for square root.<br>
                        Leave the variables 's', 'q', 'r', 't' empty <br>
                        <span class="math-text">
                            5x + sqrt(x) = <span class="math-disp">5x + \sqrt x</span>
                        </span>
                    </p>
                    <p class="card-text">
                        Use 'Abs()' for square root (uppercase 'A').<br>
                        Leave the variables 'A', 'b', 's' empty <br>
                        <span class="math-text">
                            9 / Abs(-3) = <span class="math-disp">\frac{9}{|-3|}</span>
                        </span>
                    </p>
                    <h6 class="card-title">Need more help or having issues? <a href="/contact/"><span class="math-text">Click here!</span></a></h6>
                </div>
            </div>
        </div>
        <div class="content-body2">
            <div class="pagehead">
                <h6 class="subject">General Mathematics</h6>
                Operations on Functions
                <div style="font-size: 0.7rem;">Input your functions in terms of 'x'</div>
            </div>
            <div class="container">
                <form action="" method="POST" class="form" id="form">
                    {% csrf_token %}
                    <div class="form-floating">
                        <input type="text" class="form-control" id="functioninput1" placeholder="Function" name="function1" value="{{ function1 }}" autocomplete="off">
                        <label for="functioninput1">f(x)</label>
                    </div>
                    <div><br></div>
                    <div class="form-floating">
                        <input type="text" class="form-control" id="functioninput2" placeholder="Function" name="function2" value="{{ function2 }}" autocomplete="off">
                        <label for="functioninput2">g(x)</label>
                    </div>
                    <div><br></div>
                    <div class="input-group mb-3 variableinput variable-x foperations-x">
                        <span class="input-group-text">x =</span>
                        <input type="text" class="form-control vinput" value="{{ x }}" placeholder="Enter value of 'x'" name="variable-x" autocomplete="off">
                    </div>
                    <div><br></div>
                    <select class="form-select select-op" aria-label="Default select example" name="operation">
                        <option value="1" {{ option1 }}>(f + g)(x)</option>
                        <option value="2" {{ option2 }}>(f - g)(x)</option>
                        <option value="3" {{ option3 }}>(f * g)(x)</option>
                        <option value="4" {{ option4 }}>(f / g)(x)</option>
                    </select>
                    <div><br></div>
                    <input type="submit" class="btn btn-primary" value="Solve"">
                </form>
            </div>
            <div><br></div>
        </div>
        <div class="card-container">
            <div class="card text-dark mb-3 card-right" style="max-width: 18rem;">
                <div class="card-header">Answer</div>
                <div class="card-body sample-eqs">
                    
                    {% if answer == "Nope" %}
                        <div class="answer">
                            <h6>Hmmm... Invalid input!</h6>
                            <h6>If your input is valid for you, <a href="/contact/"><span class="math-text">report the issue</span></a>.</h6>
                        </div>
                    {% elif answer %}
                        <div class="answer">
                            <h5><span class="math-disp">{{ answer }}</span></h5>
                        </div>
                    {% else %}
                        Click solve
                    {% endif %}

                    <!-- <p class="card-text">
                        <span class="math-text">
                            <span class="math-disp" id="sample1">3x - 5</span><br>
                        </span>
                    </p>        
                    <p class="card-text">
                        <span class="math-text">
                            <span class="math-disp" id="sample2">9a + 2^3^a^-^2</span><br>
                        </span>
                    </p>
                    <p class="card-text">
                        <span class="math-text">
                            <span class="math-disp" id="sample3">\frac{|6d|}{12f + 9u}</span><br>
                        </span>
                    </p>  
                    <br>
                    <h6 class="card-title">Need more help or having issues? <a href=""><span class="math-text">Click here!</span></a></h6> -->

                </div>
            </div>

            <div class="card-right next">
                <a href="{% url 'genmath:fcomposite' %}">Composition of Functions →</a>
            </div>
        </div>
    </div>

{% endblock %}

genmath/templates/genmath/index.html
{% extends "main/layout.html" %}
{% load static %}
{% block head %}
    <link rel="stylesheet" href="{% static 'genmath/styles.css' %}" type="text/css">
{% endblock %}

{% block title %}
    General Mathematics - CheckMaths
{% endblock %}

{% block body %}
    <div class="pagehead">
        <h6 class="subject">General Mathematics</h6>
        Select a topic:
    </div>
    <div class="col-12 choices">
        <a href="{% url 'genmath:fevaluation' %}" class="btn btn-primary">Evaluation of Functions</a>
        <a href="{% url 'genmath:foperations' %}" class="btn btn-primary">Operations on Functions <br> (add, subtract, multiply, divide)</a>
        <a href="{% url 'genmath:fcomposite' %}" class="btn btn-primary">Composition of Functions</a>
        <div style="color: rgb(168, 169, 170);">
            <br>
            <br>
            Other topics are coming soon!
        </div>
        <!-- <a href="" class="btn btn-primary">Topic</a>
        <a href="" class="btn btn-primary">Topic</a>
        <a href="" class="btn btn-primary">Topic</a> -->
    </div>
    





    <script>
        var popoverTriggerList = [].slice.call(document.querySelectorAll('[data-bs-toggle="popover"]'))
            var popoverList = popoverTriggerList.map(function (popoverTriggerEl) {
            return new bootstrap.Popover(popoverTriggerEl)
        })
    </script>
{% endblock %}