bscal/urls.py
from django.urls import path
from . import views

app_name = "bscal"
urlpatterns = [
    # /bscal/...
    path("", views.index, name="index"),
    path("limits/", views.limits, name="limits"),
    path("differentiation/", views.differentiation, name="differentiation"),
    # path("circle-standard-form/", views.cstdform, name="cstdform"),
    # path("circle-general-form/", views.cgrlform, name="cgrlform"),
    # path("parabola-finding-roots/", views.proots, name="proots")

]

checkmath/urls.py
from os import name
import genmath
import precal
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from django.views.generic.base import TemplateView
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^$', TemplateView.as_view(template_name='main/index.html'),
        name='home'),
    path('contact/', views.contact, name="contact"),
    url(r'^about/$', TemplateView.as_view(template_name='main/about.html'),
        name='about'),
    path('genmath/', include('genmath.urls')),
    path('precal/', include('precal.urls')),
    path('bscal/', include('bscal.urls'))
]

bscal/models.py
from django.db import models

# Create your models here.

bscal/views.py
from django.shortcuts import render
import calculations as calc

# Create your views here.


def index(request):
    return render(request, 'bscal/index.html')


def limits(request):
    if request.method == "POST":

        function = request.POST.get("function")
        c = request.POST.get("c")

        if not function or not c: 
            return render(request, "bscal/limits.html", {
                'function': '',
                'c': '',
                'answer': 'Nope'
            })

        try:
            answer = calc.getlimit(function, c)
        except:
            answer = 'Nope'
        

        return render(request, "bscal/limits.html", {
                'function': function,
                'c': c,
                'answer': answer
            })

    else:
        return render(request, 'bscal/limits.html')


def differentiation(request):
    if request.method == "POST":

        function = request.POST.get("function")
        nth = request.POST.get("nth")

        if not function:
            return render(request, "bscal/differentiation.html", {
                'function': '',
                'nth': '1',
                'answer': 'Nope'
            })

        try:
            nth = int(nth)
        except:
            return render(request, "bscal/differentiation.html", {
                'function': function,
                'nth': '1',
                'answer': 'Nope'
            })

        try:
            answer = calc.differentiate(function, nth)
        except:
            answer = 'Nope'


        return render(request, "bscal/differentiation.html", {
            'function': function,
            'nth': str(nth),
            'answer': answer
        })


    else:
        return render(request, 'bscal/differentiation.html', {
            'function': '-4x^2 - 5x - 2',
            'nth': '1',
        })

bscal/templates/bscal/differential.html
{% extends "main/layout.html" %}
{% load static %}
{% block head %}
    <link rel="stylesheet" href="{% static 'genmath/styles.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'precal/styles.css' %}" type="text/css">
    <script src="{% static 'genmath/script-foperations.js' %}" type="text/javascript"></script>

    <!-- Desmos -->
    <script src="https://www.desmos.com/api/v1.6/calculator.js?apiKey=dcb31709b452b1cf9dc26972add0fda6"></script>


    <!-- MathQuill -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/mathquill/0.10.1/mathquill.css" integrity="sha512-vPg9GqsZZ4LHv9BkFfZSXt7y4D7YaARPU2JFmpZug4EgtJJrumytMAFZkNSk2LSyqWir0TNbh2tBq7UJIMxvlA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/mathquill/0.10.1/mathquill.js" integrity="sha512-7jEhcM7FbjGHo1ejs1iw1J8FxcnACx7Z3lG29gQ5vTBe2U/gaQpzwjzPCyg32zTwXCloQDdorpLufmu0nBIqnQ==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
{% endblock %}

{% block title %}
    Differentiation - CheckMath
{% endblock %}

{% block body %}
    <nav aria-label="breadcrumb" class="notnav">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="/">Home</a></li>
            <li class="breadcrumb-item"><a href="/bscal">Basic Calculus</a></li>
            <li class="breadcrumb-item active" aria-current="page">Differentiation</li>
        </ol>
    </nav>
    <div class="content-body">
        <div class="card-container">
            <div class="card text-dark mb-3" style="max-width: 18rem;">
                <div class="card-header">Take note</div>
                <div class="card-body">
                    <p class="card-text">
                        Use '()' for 2 or more digit exponents. <br>
                        <span class="math-text">
                            x^2a = <span class="math-disp">x^2a</span><br>
                            x^(2a) = <span class="math-disp">x^2^a</span>
                        </span>
                    </p>
                    <p class="card-text">
                        Use '()' for grouping. <br>
                        <span class="math-text">
                            4x - 2 / 2x + 8 <br>= <span class="math-disp">4x -\frac{2}{2x} + 8</span><br>
                            (4x - 2) / (2x + 8) <br>= <span class="math-disp">\frac{4x - 2}{2x + 8}</span>
                        </span>
                    </p>
                    <p class="card-text">
                        Use 'sqrt()' for square root.<br>
                        Leave the variables 's', 'q', 'r', 't' empty <br>
                        <span class="math-text">
                            5x + sqrt(x) = <span class="math-disp">5x + \sqrt x</span>
                        </span>
                    </p>
                    <p class="card-text">
                        Use 'Abs()' for square root (uppercase 'A').<br>
                        Leave the variables 'A', 'b', 's' empty <br>
                        <span class="math-text">
                            9 / Abs(-3) = <span class="math-disp">\frac{9}{|-3|}</span>
                        </span>
                    </p>
                    <h6 class="card-title">Need more help or having issues? <a href=""><span class="math-text">Click here!</span></a></h6>
                </div>
            </div>
        </div>
        <div class="content-body2">
            <div class="pagehead">
                <h6 class="subject">Basic Calculus</h6>
                Limits
                <div style="font-size: 0.7rem;">Input your function in terms of 'x'</div>
            </div>
            <div class="container">
                <form action="" method="POST" class="form" id="form" style="width: 90%;">
                    {% csrf_token %}
                    <div class="input-group mb-3 variableinput variable-x">
                        <span class="input-group-text">f(x) = </span>
                        <input type="text" class="form-control vinput" value="{{ function }}" placeholder="Enter function" name="function" autocomplete="off">
                    </div>
                    <div><br></div>
                    <input type="submit" class="btn btn-primary" value="Solve"">
                    <div><br><br></div>
                </form>
            </div>
            <div><br></div>
        </div>
        <div class="card-container">
            <div class="card text-dark mb-3 card-right" style="max-width: 18rem;">
                <div class="card-header">Answer</div>
                <div class="card-body sample-eqs">
                    
                    {% if answer == "Nope" %}
                        <div class="answer">
                            <h6>Hmmm... Invalid input!</h6>
                            <h6>If your input is valid for you, <a href=""><span class="math-text">click here!</span></a></h6>
                        </div>
                    {% elif answer %}
                        <div class="answer">
                            <h5><span class="math-disp">{{ answer }}</span></h5>
                        </div>
                    {% else %}
                        Click solve
                    {% endif %}
                </div>
            </div>

        </div>
    </div>



{% endblock %}

bscal/templates/bscal/differentiation.html
{% extends "main/layout.html" %}
{% load static %}
{% block head %}
    <link rel="stylesheet" href="{% static 'genmath/styles.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'precal/styles.css' %}" type="text/css">
    <script src="{% static 'genmath/script-foperations.js' %}" type="text/javascript"></script>

    <!-- Desmos -->
    <script src="https://www.desmos.com/api/v1.6/calculator.js?apiKey=dcb31709b452b1cf9dc26972add0fda6"></script>


    <!-- MathQuill -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/mathquill/0.10.1/mathquill.css" integrity="sha512-vPg9GqsZZ4LHv9BkFfZSXt7y4D7YaARPU2JFmpZug4EgtJJrumytMAFZkNSk2LSyqWir0TNbh2tBq7UJIMxvlA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/mathquill/0.10.1/mathquill.js" integrity="sha512-7jEhcM7FbjGHo1ejs1iw1J8FxcnACx7Z3lG29gQ5vTBe2U/gaQpzwjzPCyg32zTwXCloQDdorpLufmu0nBIqnQ==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
{% endblock %}

{% block title %}
    Differentiation - CheckMaths
{% endblock %}

{% block body %}
    <nav aria-label="breadcrumb" class="notnav">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="/">Home</a></li>
            <li class="breadcrumb-item"><a href="/bscal">Basic Calculus</a></li>
            <li class="breadcrumb-item active" aria-current="page">Differentiation</li>
        </ol>
    </nav>
    <div class="content-body">
        <div class="card-container">
            <div class="card text-dark mb-3" style="max-width: 18rem;">
                <div class="card-header">Take note</div>
                <div class="card-body">
                    <p class="card-text">
                        Use '()' for 2 or more digit exponents. <br>
                        <span class="math-text">
                            x^2a = <span class="math-disp">x^2a</span><br>
                            x^(2a) = <span class="math-disp">x^2^a</span>
                        </span>
                    </p>
                    <p class="card-text">
                        Use '()' for grouping. <br>
                        <span class="math-text">
                            4x - 2 / 2x + 8 <br>= <span class="math-disp">4x -\frac{2}{2x} + 8</span><br>
                            (4x - 2) / (2x + 8) <br>= <span class="math-disp">\frac{4x - 2}{2x + 8}</span>
                        </span>
                    </p>
                    <p class="card-text">
                        Use 'sqrt()' for square root.<br>
                        Leave the variables 's', 'q', 'r', 't' empty <br>
                        <span class="math-text">
                            5x + sqrt(x) = <span class="math-disp">5x + \sqrt x</span>
                        </span>
                    </p>
                    <p class="card-text">
                        Use 'Abs()' for square root (uppercase 'A').<br>
                        Leave the variables 'A', 'b', 's' empty <br>
                        <span class="math-text">
                            9 / Abs(-3) = <span class="math-disp">\frac{9}{|-3|}</span>
                        </span>
                    </p>
                    <h6 class="card-title">Need more help or having issues? <a href="/contact/"><span class="math-text">Click here!</span></a></h6>
                </div>
            </div>
        </div>
        <div class="content-body2">
            <div class="pagehead">
                <h6 class="subject">Basic Calculus</h6>
                Limits
                <div style="font-size: 0.7rem;">Input your function in terms of 'x'</div>
            </div>
            <div class="container">
                <form action="" method="POST" class="form" id="form" style="width: 90%;">
                    {% csrf_token %}
                    <div class="input-group mb-3 variableinput variable-x">
                        <span class="input-group-text">f(x) = </span>
                        <input type="text" class="form-control vinput" value="{{ function }}" placeholder="Enter function" name="function" autocomplete="off">
                    </div>
                    <div><br></div>
                    <div style="text-align: center;">
                        Differentiate <input type="text" name="nth" value="{{ nth }}" class="small-input"> times
                    </div>
                    <div><br></div>
                    <input type="submit" class="btn btn-primary" value="Solve"">
                    <div><br><br></div>
                </form>
            </div>
            <div><br></div>
        </div>
        <div class="card-container">
            <div class="card text-dark mb-3 card-right" style="max-width: 18rem;">
                <div class="card-header">Answer</div>
                <div class="card-body sample-eqs">
                    
                    {% if answer == "Nope" %}
                        <div class="answer">
                            <h6>Hmmm... Invalid input!</h6>
                            <h6>If your input is valid for you, <a href="/contact/"><span class="math-text">report the issue</span></a>.</h6>
                        </div>
                    {% elif answer %}
                        <div class="answer">
                            <h5><span class="math-disp">{{ answer }}</span></h5>
                        </div>
                    {% else %}
                        Click solve
                    {% endif %}
                </div>
            </div>

        </div>
    </div>



{% endblock %}

bscal/templates/bscal/index.html
{% extends "main/layout.html" %}
{% load static %}
{% block head %}
    <link rel="stylesheet" href="{% static 'genmath/styles.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'precal/styles.css' %}" type="text/css">
{% endblock %}

{% block title %}
    Basic Calculus - CheckMaths
{% endblock %}

{% block body %}
    <div class="pagehead">
        <h6 class="subject">Basic Calculus</h6>
        Select a topic:
    </div>
    <div class="col-12 choices">
        <a href="{% url 'bscal:limits' %}" class="btn btn-primary">Limits</a>
        <a href="{% url 'bscal:differentiation' %}" class="btn btn-primary">Differentiation</a>
        <a href="#" class="btn btn-primary disabled">Integration</a>
        <div style="color: rgb(168, 169, 170);">
            <br>
            <br>
            Other topics are coming soon!
        </div>
        <!-- <a href="" class="btn btn-primary">Topic</a>
        <a href="" class="btn btn-primary">Topic</a>
        <a href="" class="btn btn-primary">Topic</a> -->
    </div>
    




{% endblock %}

bscal/templates/bscal/limit.html
{% extends "main/layout.html" %}
{% load static %}
{% block head %}
    <link rel="stylesheet" href="{% static 'genmath/styles.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'precal/styles.css' %}" type="text/css">
    <script src="{% static 'genmath/script-foperations.js' %}" type="text/javascript"></script>

    <!-- Desmos -->
    <script src="https://www.desmos.com/api/v1.6/calculator.js?apiKey=dcb31709b452b1cf9dc26972add0fda6"></script>


    <!-- MathQuill -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/mathquill/0.10.1/mathquill.css" integrity="sha512-vPg9GqsZZ4LHv9BkFfZSXt7y4D7YaARPU2JFmpZug4EgtJJrumytMAFZkNSk2LSyqWir0TNbh2tBq7UJIMxvlA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/mathquill/0.10.1/mathquill.js" integrity="sha512-7jEhcM7FbjGHo1ejs1iw1J8FxcnACx7Z3lG29gQ5vTBe2U/gaQpzwjzPCyg32zTwXCloQDdorpLufmu0nBIqnQ==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
{% endblock %}

{% block title %}
    Parabola: Finding Roots - CheckMath
{% endblock %}

{% block body %}
    <nav aria-label="breadcrumb" class="notnav">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="/">Home</a></li>
            <li class="breadcrumb-item"><a href="/precal">Pre-Calculus</a></li>
            <li class="breadcrumb-item active" aria-current="page">Parabola: Finding Roots</li>
        </ol>
    </nav>
    <div class="content-body">
        <div class="card-container">
            <div class="card text-dark mb-3" style="max-width: 18rem;">
                <div class="card-header">Take note</div>
                <div class="card-body">
                    <p class="card-text">
                        Use '()' for 2 or more digit exponents. <br>
                        <span class="math-text">
                            x^2a = <span class="math-disp">x^2a</span><br>
                            x^(2a) = <span class="math-disp">x^2^a</span>
                        </span>
                    </p>
                    <p class="card-text">
                        Use '()' for grouping. <br>
                        <span class="math-text">
                            4x - 2 / 2x + 8 <br>= <span class="math-disp">4x -\frac{2}{2x} + 8</span><br>
                            (4x - 2) / (2x + 8) <br>= <span class="math-disp">\frac{4x - 2}{2x + 8}</span>
                        </span>
                    </p>
                    <p class="card-text">
                        Use 'sqrt()' for square root.<br>
                        Leave the variables 's', 'q', 'r', 't' empty <br>
                        <span class="math-text">
                            5x + sqrt(x) = <span class="math-disp">5x + \sqrt x</span>
                        </span>
                    </p>
                    <p class="card-text">
                        Use 'Abs()' for square root (uppercase 'A').<br>
                        Leave the variables 'A', 'b', 's' empty <br>
                        <span class="math-text">
                            9 / Abs(-3) = <span class="math-disp">\frac{9}{|-3|}</span>
                        </span>
                    </p>
                    <h6 class="card-title">Need more help or having issues? <a href=""><span class="math-text">Click here!</span></a></h6>
                </div>
            </div>
        </div>
        <div class="content-body2">
            <div class="pagehead">
                <h6 class="subject">Pre-Calculus</h6>
                Parabola: Finding Roots
                <div style="font-size: 0.7rem;">Input your function in terms of 'x'</div>
            </div>
            <div class="container">
                <form action="" method="POST" class="form" id="form" style="width: 90%;">
                    {% csrf_token %}
                    <div class="form-floating" style="width: auto;">
                        <input type="text" class="form-control" id="functioninput" placeholder="Function" name="function" value="{{ function }}" autocomplete="off">
                        <label for="functioninput">Standard Form</label>
                    </div>
                    <div style="font-size: 0.7rem; margin-top: 10px; text-align: center;">Standard Form of Parabola is: <span class="math-disp">ax^2 + bx + c</span></div>
                    <div><br></div>
                    <input type="submit" class="btn btn-primary" value="Solve"">
                    <div><br><br></div>
                </form>
            </div>
            <div><br></div>
        </div>
        <div class="card-container">
            <div class="card text-dark mb-3 card-right" style="max-width: 18rem;">
                <div class="card-header">Answer</div>
                <div class="card-body sample-eqs">
                    
                    {% if answer == "Nope" %}
                        <div class="answer">
                            <h6>Hmmm... Invalid input!</h6>
                            <h6>If your input is valid for you, <a href=""><span class="math-text">click here!</span></a></h6>
                        </div>
                    {% elif answer %}
                        <div class="answer">
                            <h5><span class="math-disp">{{ answer }}</span></h5>
                        </div>
                    {% else %}
                        Click solve
                    {% endif %}
                </div>
            </div>

        </div>
    </div>



{% endblock %}

bscal/templates/bscal/limits.html
{% extends "main/layout.html" %}
{% load static %}
{% block head %}
    <link rel="stylesheet" href="{% static 'genmath/styles.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'precal/styles.css' %}" type="text/css">
    <script src="{% static 'genmath/script-foperations.js' %}" type="text/javascript"></script>

    <!-- Desmos -->
    <script src="https://www.desmos.com/api/v1.6/calculator.js?apiKey=dcb31709b452b1cf9dc26972add0fda6"></script>


    <!-- MathQuill -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/mathquill/0.10.1/mathquill.css" integrity="sha512-vPg9GqsZZ4LHv9BkFfZSXt7y4D7YaARPU2JFmpZug4EgtJJrumytMAFZkNSk2LSyqWir0TNbh2tBq7UJIMxvlA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/mathquill/0.10.1/mathquill.js" integrity="sha512-7jEhcM7FbjGHo1ejs1iw1J8FxcnACx7Z3lG29gQ5vTBe2U/gaQpzwjzPCyg32zTwXCloQDdorpLufmu0nBIqnQ==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
{% endblock %}

{% block title %}
    Limits - CheckMaths
{% endblock %}

{% block body %}
    <nav aria-label="breadcrumb" class="notnav">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="/">Home</a></li>
            <li class="breadcrumb-item"><a href="/bscal">Basic Calculus</a></li>
            <li class="breadcrumb-item active" aria-current="page">Limits</li>
        </ol>
    </nav>
    <div class="content-body">
        <div class="card-container">
            <div class="card text-dark mb-3" style="max-width: 18rem;">
                <div class="card-header">Take note</div>
                <div class="card-body">
                    <p class="card-text">
                        Use '()' for 2 or more digit exponents. <br>
                        <span class="math-text">
                            x^2a = <span class="math-disp">x^2a</span><br>
                            x^(2a) = <span class="math-disp">x^2^a</span>
                        </span>
                    </p>
                    <p class="card-text">
                        Use '()' for grouping. <br>
                        <span class="math-text">
                            4x - 2 / 2x + 8 <br>= <span class="math-disp">4x -\frac{2}{2x} + 8</span><br>
                            (4x - 2) / (2x + 8) <br>= <span class="math-disp">\frac{4x - 2}{2x + 8}</span>
                        </span>
                    </p>
                    <p class="card-text">
                        Use 'sqrt()' for square root.<br>
                        Leave the variables 's', 'q', 'r', 't' empty <br>
                        <span class="math-text">
                            5x + sqrt(x) = <span class="math-disp">5x + \sqrt x</span>
                        </span>
                    </p>
                    <p class="card-text">
                        Use 'Abs()' for square root (uppercase 'A').<br>
                        Leave the variables 'A', 'b', 's' empty <br>
                        <span class="math-text">
                            9 / Abs(-3) = <span class="math-disp">\frac{9}{|-3|}</span>
                        </span>
                    </p>
                    <h6 class="card-title">Need more help or having issues? <a href="/contact/"><span class="math-text">Click here!</span></a></h6>
                </div>
            </div>
        </div>
        <div class="content-body2">
            <div class="pagehead">
                <h6 class="subject">Basic Calculus</h6>
                Limits
                <div style="font-size: 0.7rem;">Input your function in terms of 'x'</div>
            </div>
            <div class="container">
                <form action="" method="POST" class="form" id="form" style="width: 90%;">
                    {% csrf_token %}
                    <div class="input-group mb-3 variableinput variable-x">
                        <span class="input-group-text">lim <br> x → c</span>
                        <input type="text" class="form-control vinput" value="{{ function }}" placeholder="Enter function" name="function" autocomplete="off">
                    </div>
                    <div><br></div>
                    <div class="input-group mb-3 variableinput variable-x">
                        <span class="input-group-text"> c = </span>
                        <input type="text" class="form-control vinput" value="{{ c }}" placeholder="Enter value of 'c" name="c" autocomplete="off">
                    </div>
                    <div><br></div>
                    <input type="submit" class="btn btn-primary" value="Solve"">
                    <div><br><br></div>
                </form>
            </div>
            <div><br></div>
        </div>
        <div class="card-container">
            <div class="card text-dark mb-3 card-right" style="max-width: 18rem;">
                <div class="card-header">Answer</div>
                <div class="card-body sample-eqs">
                    
                    {% if answer == "Nope" %}
                        <div class="answer">
                            <h6>Hmmm... Invalid input!</h6>
                            <h6>If your input is valid for you, <a href="/contact/"><span class="math-text">report the issue</span></a>.</h6>
                        </div>
                    {% elif answer %}
                        <div class="answer">
                            <h5><span class="math-disp">{{ answer }}</span></h5>
                        </div>
                    {% else %}
                        Click solve
                    {% endif %}
                </div>
            </div>

        </div>
    </div>



{% endblock %}